[package]
name = "anchor_counter_interface"
version = "0.1.0"
edition = "2021"

[dependencies.borsh]
version = "1.5.1"

[dependencies.serde]
optional = true
version = "1.0.203"

[dependencies.solana-program]
version = "1.18.15"
