[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "9T8kfAVE56hd7h7mTq1rBE7aFcJhkq82Rq3ZU8f7vut8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
